/// BEGIN AUTOGENERATED SECTION - MODIFICATIONS TO THIS CODE WILL BE OVERWRITTEN

/// globals.h
/// Autogenerated by telem_defines_globals_generate.py on Fri Dec 18 16:16:57 2020

#include <stdint.h>

extern uint32_t valve_states;
extern float ebatt;
extern float ibus;
extern uint8_t STATE;
extern float e3v;
extern float e5v;
extern float e28v;
extern float i5v;
extern float i3v;
extern uint8_t last_command_id;
extern float pressure[8];
extern float load[8];
extern float ivlv[8];
extern float evlv[8];
extern float tc[8];
extern float rtd[8];
extern float i_mtr_ab[4];
extern float i_mtr[2];
extern float pot[4];
