/// BEGIN AUTOGENERATED SECTION - MODIFICATIONS TO THIS CODE WILL BE OVERWRITTEN

/// globals.h
/// Autogenerated by firmware-libraries/SerialComms/python/telem_file_generator.py on Fri Jan 15 02:20:09 2021

#ifndef INC_GLOBALS_H_
#define INC_GLOBALS_H_
#include <stdint.h>

extern uint32_t valve_states;
extern float e_batt;
extern float i_batt;
extern enum States STATE;
extern float e3v;
extern float e5v;
extern float i5v;
extern float i3v;
extern uint8_t last_command_id;
extern uint64_t micros;
extern uint32_t telem_rate;
extern uint32_t adc_rate;
extern uint8_t own_board_addr;
extern float pressure[6];
extern float ivlv[9];
extern float evlv[9];
extern float tc[5];
extern float i_mtr_ab[4];
extern float i_mtr[2];
extern float epot[4];

/// END AUTOGENERATED SECTION - USER CODE GOES BELOW THIS LINE

#endif /*INC_GLOBALS_H*/
=======
/// BEGIN AUTOGENERATED SECTION - MODIFICATIONS TO THIS CODE WILL BE OVERWRITTEN

/// globals.h
/// Autogenerated by firmware-libraries/SerialComms/python/telem_file_generator.py on Mon Jan  4 15:28:24 2021

#include <stdint.h>

extern uint32_t valve_states;
extern float e_batt;
extern float i_batt;
extern enum States STATE;
extern float e3v;
extern float e5v;
extern float i5v;
extern float i3v;
extern uint8_t last_command_id;
extern uint64_t micros;
extern uint32_t telem_rate;
extern uint32_t adc_rate;
extern uint8_t own_board_addr;
extern float pressure[6];
extern float ivlv[8];
extern float evlv[8];
extern float i_mtr_ab[4];
extern float i_mtr[2];
extern float epot[4];
>>>>>>> aca095bb1e815f68b0dc99df983c61e085222fbc
