/// BEGIN AUTOGENERATED SECTION - MODIFICATIONS TO THIS CODE WILL BE OVERWRITTEN

/// globals.h
/// Autogenerated by telem_file_generator.py on Thu Dec 24 19:51:28 2020

#include <stdint.h>

extern uint32_t valve_states;
extern float e_batt;
extern float i_batt;
extern enum States STATE;
extern float e3v;
extern float e5v;
extern float i5v;
extern float i3v;
extern uint8_t last_command_id;
extern uint64_t micros;
extern uint32_t telem_rate;
extern uint32_t adc_rate;
extern uint8_t own_board_addr;
extern float pressure[6];
extern float ivlv[8];
extern float evlv[8];
extern float i_mtr_ab[4];
extern float i_mtr[2];
extern float epot[4];
