// to be autogenerated from master commands file
#ifndef PACK_CMD_DEFINES_H
#define PACK_CMD_DEFINES_H
#define NUM_CMD_ITEMS     3
#include <stdint.h>

void cmd0_ptr(uint8_t* data, uint8_t* status);

void cmd1_ptr(uint8_t* data, uint8_t* status);

void cmd2_ptr(uint8_t* data, uint8_t* status);

void (*cmds_ptr[NUM_CMD_ITEMS])(uint8_t* x, uint8_t* y);

// Note: to call a function do
/**
 * (*cmds_ptr[0])(array ptr here)
 */
#endif
