// to be autogenerated from master commands file
#ifndef PACK_CMD_DEFINES_H
#define PACK_CMD_DEFINES_H
#define NUM_CMD_ITEMS     3
#include <stdint.h>

void digital_write(uint8_t* data, uint8_t* status);

void cmd1_ptr(uint8_t* data, uint8_t* status);

void cmd2_ptr(uint8_t* data, uint8_t* status);

typedef void (*Cmd_Pointer)(uint8_t* x, uint8_t* y);

static Cmd_Pointer cmds_ptr[NUM_CMD_ITEMS] = {
cmd0_ptr,
cmd1_ptr,
cmd2_ptr
};

// Note: to call a function do
/**
 * (*cmds_ptr[0])(array ptr here)
 *
 * The actual cmd functions will be defined in a separate c file by the firwmare
 * developer for each board. They simply need to include this header file
 * in the c file in which they define the function. This allows the developer
 * to import/use any variables or typedefs from the hal library. This file is
 * simply the jumptable that gives the comms library an easy way to call
 * custom functions without additional knowledge of where this file is defined
 *
 */
#endif
