// will be autogenerated from byte_template_packet.txt file
#include <stdint.h>
#include "globals.h"

extern void pack_telem_data(uint8_t* dst);

#define NUM_TELEM_ITEMS             71
#define TELEM_ITEM_0    ((uint32_t) (valve_states*1)) >> 0
#define TELEM_ITEM_1    ((uint32_t) (valve_states*1)) >> 8
#define TELEM_ITEM_2    ((uint32_t) (valve_states*1)) >> 16
#define TELEM_ITEM_3    ((uint32_t) (valve_states*1)) >> 24
#define TELEM_ITEM_4    ((int16_t) (pressure[0]*1)) >> 0
#define TELEM_ITEM_5    ((int16_t) (pressure[0]*1)) >> 8
#define TELEM_ITEM_6    ((int16_t) (pressure[1]*1)) >> 0
#define TELEM_ITEM_7    ((int16_t) (pressure[1]*1)) >> 8
#define TELEM_ITEM_8    ((int16_t) (pressure[2]*1)) >> 0
#define TELEM_ITEM_9    ((int16_t) (pressure[2]*1)) >> 8
#define TELEM_ITEM_10   ((int16_t) (pressure[3]*1)) >> 0
#define TELEM_ITEM_11   ((int16_t) (pressure[3]*1)) >> 8
#define TELEM_ITEM_12   ((int16_t) (pressure[4]*1)) >> 0
#define TELEM_ITEM_13   ((int16_t) (pressure[4]*1)) >> 8
#define TELEM_ITEM_14   ((int16_t) (pressure[5]*1)) >> 0
#define TELEM_ITEM_15   ((int16_t) (pressure[5]*1)) >> 8
#define TELEM_ITEM_16   ((int16_t) (pressure[6]*1)) >> 0
#define TELEM_ITEM_17   ((int16_t) (pressure[6]*1)) >> 8
#define TELEM_ITEM_18   ((int16_t) (pressure[7]*1)) >> 0
#define TELEM_ITEM_19   ((int16_t) (pressure[7]*1)) >> 8
#define TELEM_ITEM_20   ((int16_t) (ebatt*1000)) >> 0
#define TELEM_ITEM_21   ((int16_t) (ebatt*1000)) >> 8
#define TELEM_ITEM_22   ((int16_t) (ibus*100)) >> 0
#define TELEM_ITEM_23   ((int16_t) (ibus*100)) >> 8
#define TELEM_ITEM_24   ((uint8_t) (STATE*1)) >> 0
#define TELEM_ITEM_25   ((uint8_t) (ivlv[0]*10)) >> 0
#define TELEM_ITEM_26   ((uint8_t) (ivlv[1]*10)) >> 0
#define TELEM_ITEM_27   ((uint8_t) (ivlv[2]*10)) >> 0
#define TELEM_ITEM_28   ((uint8_t) (ivlv[3]*10)) >> 0
#define TELEM_ITEM_29   ((uint8_t) (ivlv[4]*10)) >> 0
#define TELEM_ITEM_30   ((uint8_t) (ivlv[5]*10)) >> 0
#define TELEM_ITEM_31   ((uint8_t) (ivlv[6]*10)) >> 0
#define TELEM_ITEM_32   ((uint8_t) (ivlv[7]*10)) >> 0
#define TELEM_ITEM_33  ((uint8_t) (evlv[0]*10)) >> 0
#define TELEM_ITEM_34  ((uint8_t) (evlv[1]*10)) >> 0
#define TELEM_ITEM_35  ((uint8_t) (evlv[2]*10)) >> 0
#define TELEM_ITEM_36  ((uint8_t) (evlv[3]*10)) >> 0
#define TELEM_ITEM_37  ((uint8_t) (evlv[4]*10)) >> 0
#define TELEM_ITEM_38  ((uint8_t) (evlv[5]*10)) >> 0
#define TELEM_ITEM_39  ((uint8_t) (evlv[6]*10)) >> 0
#define TELEM_ITEM_40  ((uint8_t) (evlv[7]*10)) >> 0
#define TELEM_ITEM_41  ((int32_t) (e3v*100)) >> 0
#define TELEM_ITEM_42  ((int32_t) (e3v*100)) >> 8
#define TELEM_ITEM_43  ((int32_t) (e3v*100)) >> 16
#define TELEM_ITEM_44  ((int32_t) (e3v*100)) >> 24
#define TELEM_ITEM_45  ((int32_t) (e5v*100)) >> 0
#define TELEM_ITEM_46  ((int32_t) (e5v*100)) >> 8
#define TELEM_ITEM_47  ((int32_t) (e5v*100)) >> 16
#define TELEM_ITEM_48  ((int32_t) (e5v*100)) >> 24
#define TELEM_ITEM_49  ((int16_t) (e28v*100)) >> 0
#define TELEM_ITEM_50  ((int16_t) (e28v*100)) >> 8
#define TELEM_ITEM_51  ((uint8_t) (i5v*100)) >> 0
#define TELEM_ITEM_52  ((uint8_t) (i3v*100)) >> 0
#define TELEM_ITEM_53  ((uint16_t) (last_command_id*1)) >> 0
#define TELEM_ITEM_54  ((uint16_t) (last_command_id*1)) >> 8
#define TELEM_ITEM_55  ((int16_t) (tc[0]*1)) >> 0
#define TELEM_ITEM_56  ((int16_t) (tc[0]*1)) >> 8
#define TELEM_ITEM_57  ((uint16_t) (tc[1]*1)) >> 0
#define TELEM_ITEM_58  ((uint16_t) (tc[1]*1)) >> 8
#define TELEM_ITEM_59  ((uint16_t) (tc[2]*1)) >> 0
#define TELEM_ITEM_60  ((uint16_t) (tc[2]*1)) >> 8
#define TELEM_ITEM_61  ((uint16_t) (tc[3]*1)) >> 0
#define TELEM_ITEM_62  ((uint16_t) (tc[3]*1)) >> 8
#define TELEM_ITEM_63  ((uint16_t) (tc[4]*1)) >> 0
#define TELEM_ITEM_64  ((uint16_t) (tc[4]*1)) >> 8
#define TELEM_ITEM_65  ((uint16_t) (tc[5]*1)) >> 0
#define TELEM_ITEM_66  ((uint16_t) (tc[5]*1)) >> 8
#define TELEM_ITEM_67  ((uint16_t) (tc[6]*1)) >> 0
#define TELEM_ITEM_68  ((uint16_t) (tc[6]*1)) >> 8
#define TELEM_ITEM_69  ((uint16_t) (tc[7]*1)) >> 0
#define TELEM_ITEM_70  ((uint16_t) (tc[7]*1)) >> 8

//void pack_telem_data(uint8_t* dst);
