/// BEGIN AUTOGENERATED SECTION - MODIFICATIONS TO THIS CODE WILL BE OVERWRITTEN

/// pack_telem_defines.h
/// Autogenerated by firmware-libraries/SerialComms/python/telem_file_generator.py on Sat Jan  9 21:34:22 2021

#include "globals.h"
#include <stdint.h>

#define	TELEM_ITEM_0	((uint32_t) (valve_states*1)) >> 0 
#define	TELEM_ITEM_1	((uint32_t) (valve_states*1)) >> 8 
#define	TELEM_ITEM_2	((uint32_t) (valve_states*1)) >> 16 
#define	TELEM_ITEM_3	((uint32_t) (valve_states*1)) >> 24 
#define	TELEM_ITEM_4	((int16_t) (pressure[0]*1)) >> 0 
#define	TELEM_ITEM_5	((int16_t) (pressure[0]*1)) >> 8 
#define	TELEM_ITEM_6	((int16_t) (pressure[1]*1)) >> 0 
#define	TELEM_ITEM_7	((int16_t) (pressure[1]*1)) >> 8 
#define	TELEM_ITEM_8	((int16_t) (pressure[2]*1)) >> 0 
#define	TELEM_ITEM_9	((int16_t) (pressure[2]*1)) >> 8 
#define	TELEM_ITEM_10	((int16_t) (pressure[3]*1)) >> 0 
#define	TELEM_ITEM_11	((int16_t) (pressure[3]*1)) >> 8 
#define	TELEM_ITEM_12	((int16_t) (pressure[4]*1)) >> 0 
#define	TELEM_ITEM_13	((int16_t) (pressure[4]*1)) >> 8 
#define	TELEM_ITEM_14	((int16_t) (pressure[5]*1)) >> 0 
#define	TELEM_ITEM_15	((int16_t) (pressure[5]*1)) >> 8 
#define	TELEM_ITEM_16	((int16_t) (e_batt*1000)) >> 0 
#define	TELEM_ITEM_17	((int16_t) (e_batt*1000)) >> 8 
#define	TELEM_ITEM_18	((int16_t) (i_batt*100)) >> 0 
#define	TELEM_ITEM_19	((int16_t) (i_batt*100)) >> 8 
#define	TELEM_ITEM_20	((uint8_t) (STATE*1)) >> 0 
#define	TELEM_ITEM_21	((uint8_t) (ivlv[0]*10)) >> 0 
#define	TELEM_ITEM_22	((uint8_t) (ivlv[1]*10)) >> 0 
#define	TELEM_ITEM_23	((uint8_t) (ivlv[2]*10)) >> 0 
#define	TELEM_ITEM_24	((uint8_t) (ivlv[3]*10)) >> 0 
#define	TELEM_ITEM_25	((uint8_t) (ivlv[4]*10)) >> 0 
#define	TELEM_ITEM_26	((uint8_t) (ivlv[5]*10)) >> 0 
#define	TELEM_ITEM_27	((uint8_t) (ivlv[6]*10)) >> 0 
#define	TELEM_ITEM_28	((uint8_t) (ivlv[7]*10)) >> 0 
#define	TELEM_ITEM_29	((uint8_t) (ivlv[8]*10)) >> 0 
#define	TELEM_ITEM_30	((uint8_t) (evlv[0]*10)) >> 0 
#define	TELEM_ITEM_31	((uint8_t) (evlv[1]*10)) >> 0 
#define	TELEM_ITEM_32	((uint8_t) (evlv[2]*10)) >> 0 
#define	TELEM_ITEM_33	((uint8_t) (evlv[3]*10)) >> 0 
#define	TELEM_ITEM_34	((uint8_t) (evlv[4]*10)) >> 0 
#define	TELEM_ITEM_35	((uint8_t) (evlv[5]*10)) >> 0 
#define	TELEM_ITEM_36	((uint8_t) (evlv[6]*10)) >> 0 
#define	TELEM_ITEM_37	((uint8_t) (evlv[7]*10)) >> 0 
#define	TELEM_ITEM_38	((uint8_t) (evlv[8]*10)) >> 0 
#define	TELEM_ITEM_39	((int32_t) (e3v*100)) >> 0 
#define	TELEM_ITEM_40	((int32_t) (e3v*100)) >> 8 
#define	TELEM_ITEM_41	((int32_t) (e3v*100)) >> 16 
#define	TELEM_ITEM_42	((int32_t) (e3v*100)) >> 24 
#define	TELEM_ITEM_43	((int32_t) (e5v*100)) >> 0 
#define	TELEM_ITEM_44	((int32_t) (e5v*100)) >> 8 
#define	TELEM_ITEM_45	((int32_t) (e5v*100)) >> 16 
#define	TELEM_ITEM_46	((int32_t) (e5v*100)) >> 24 
#define	TELEM_ITEM_47	((uint8_t) (i5v*100)) >> 0 
#define	TELEM_ITEM_48	((uint8_t) (i3v*100)) >> 0 
#define	TELEM_ITEM_49	((uint16_t) (last_command_id*100)) >> 0 
#define	TELEM_ITEM_50	((uint16_t) (last_command_id*100)) >> 8 
#define	TELEM_ITEM_51	((uint16_t) (tc[0]*100)) >> 0 
#define	TELEM_ITEM_52	((uint16_t) (tc[0]*100)) >> 8 
#define	TELEM_ITEM_53	((uint16_t) (tc[1]*100)) >> 0 
#define	TELEM_ITEM_54	((uint16_t) (tc[1]*100)) >> 8 
#define	TELEM_ITEM_55	((uint16_t) (tc[2]*100)) >> 0 
#define	TELEM_ITEM_56	((uint16_t) (tc[2]*100)) >> 8 
#define	TELEM_ITEM_57	((uint16_t) (tc[3]*100)) >> 0 
#define	TELEM_ITEM_58	((uint16_t) (tc[3]*100)) >> 8 
#define	TELEM_ITEM_59	((uint16_t) (tc[4]*100)) >> 0 
#define	TELEM_ITEM_60	((uint16_t) (tc[4]*100)) >> 8 
#define	TELEM_ITEM_61	((uint16_t) (i_mtr_ab[0]*100)) >> 0 
#define	TELEM_ITEM_62	((uint16_t) (i_mtr_ab[0]*100)) >> 8 
#define	TELEM_ITEM_63	((uint16_t) (i_mtr_ab[1]*100)) >> 0 
#define	TELEM_ITEM_64	((uint16_t) (i_mtr_ab[1]*100)) >> 8 
#define	TELEM_ITEM_65	((uint16_t) (i_mtr_ab[2]*100)) >> 0 
#define	TELEM_ITEM_66	((uint16_t) (i_mtr_ab[2]*100)) >> 8 
#define	TELEM_ITEM_67	((uint16_t) (i_mtr_ab[3]*100)) >> 0 
#define	TELEM_ITEM_68	((uint16_t) (i_mtr_ab[3]*100)) >> 8 
#define	TELEM_ITEM_69	((uint16_t) (i_mtr[0]*100)) >> 0 
#define	TELEM_ITEM_70	((uint16_t) (i_mtr[0]*100)) >> 8 
#define	TELEM_ITEM_71	((uint16_t) (i_mtr[1]*100)) >> 0 
#define	TELEM_ITEM_72	((uint16_t) (i_mtr[1]*100)) >> 8 
#define	TELEM_ITEM_73	((uint16_t) (epot[0]*1000)) >> 0 
#define	TELEM_ITEM_74	((uint16_t) (epot[0]*1000)) >> 8 
#define	TELEM_ITEM_75	((uint16_t) (epot[1]*1000)) >> 0 
#define	TELEM_ITEM_76	((uint16_t) (epot[1]*1000)) >> 8 
#define	TELEM_ITEM_77	((uint16_t) (epot[2]*1000)) >> 0 
#define	TELEM_ITEM_78	((uint16_t) (epot[2]*1000)) >> 8 
#define	TELEM_ITEM_79	((uint16_t) (epot[3]*1000)) >> 0 
#define	TELEM_ITEM_80	((uint16_t) (epot[3]*1000)) >> 8 
#define	TELEM_ITEM_81	((uint64_t) (micros*1)) >> 0 
#define	TELEM_ITEM_82	((uint64_t) (micros*1)) >> 8 
#define	TELEM_ITEM_83	((uint64_t) (micros*1)) >> 16 
#define	TELEM_ITEM_84	((uint64_t) (micros*1)) >> 24 
#define	TELEM_ITEM_85	((uint64_t) (micros*1)) >> 32 
#define	TELEM_ITEM_86	((uint64_t) (micros*1)) >> 40 
#define	TELEM_ITEM_87	((uint64_t) (micros*1)) >> 48 
#define	TELEM_ITEM_88	((uint64_t) (micros*1)) >> 56 
#define	TELEM_ITEM_89	((uint32_t) (telem_rate*1)) >> 0 
#define	TELEM_ITEM_90	((uint32_t) (telem_rate*1)) >> 8 
#define	TELEM_ITEM_91	((uint32_t) (telem_rate*1)) >> 16 
#define	TELEM_ITEM_92	((uint32_t) (telem_rate*1)) >> 24 
#define	TELEM_ITEM_93	((uint32_t) (adc_rate*1)) >> 0 
#define	TELEM_ITEM_94	((uint32_t) (adc_rate*1)) >> 8 
#define	TELEM_ITEM_95	((uint32_t) (adc_rate*1)) >> 16 
#define	TELEM_ITEM_96	((uint32_t) (adc_rate*1)) >> 24 
#define	TELEM_ITEM_97	((uint8_t) (own_board_addr*1)) >> 0 
#define	CLB_NUM_TELEM_ITEMS	98

/**
 * Takes in a uint8_t array of size CLB_NUM_TELEM_ITEMS and packs the 
 * global variables into it as defined in pack_telem_defines.h
 *
 * @param dst	<uint8_t*>	Array to write the global variables to after packing their bytes for telemetry.
**/
extern void pack_telem_data(uint8_t* dst);
