/// BEGIN AUTOGENERATED SECTION - MODIFICATIONS TO THIS CODE WILL BE OVERWRITTEN

/// globals.c
/// Autogenerated by telem_defines_globals_generate.py on Sun Nov 15 13:30:30 2020

#include "globals.h"

uint32_t valve_states = 0;
float ebatt = 0;
float ibus = 0;
uint8_t STATE = 0;
float e3v = 0;
float e5v = 0;
float e28v = 0;
float i5v = 0;
float i3v = 0;
uint8_t last_command_id = 0;
float pressure[8] = {0};
float load[8] = {0};
float ivlv[8] = {0};
float evlv[8] = {0};
float tc[8] = {0};
float rtd[8] = {0};
float i_mtr_ab[4] = {0};
float i_mtr[2] = {0};
float pot[4] = {0};

/// END AUTOGENERATED SECTION - USER CODE GOES BELOW THIS LINE
