import time
import struct

class ECParse:

	def __init__(self):
		self.csv_header = "Time (s),valve_states (),pressure[0] (counts),pressure[1] (counts),pressure[2] (counts),pressure[3] (counts),pressure[4] (counts),pressure[5] (counts),pressure[6] (counts),pressure[7] (counts),ebatt (Volts),main_cycle_time (Amps),motor_cycle_time (),adc_cycle_time (counts),telemetry_cycle_time (counts),load[2] (counts),load[3] (counts),telemetry_rate (counts),load[5] (counts),load[6] (counts),load[7] (counts),ivlv[0] (Amps),ivlv[1] (Amps),ivlv[2] (Amps),ivlv[3] (Amps),ivlv[4] (Amps),ivlv[5] (Amps),ivlv[6] (Amps),ivlv[7] (Amps),evlv[0] (Volts),evlv[1] (Volts),evlv[2] (Volts),evlv[3] (Volts),evlv[4] (Volts),evlv[5] (Volts),evlv[6] (Volts),evlv[7] (Volts),e3v (Volts),e5v (Volts),e28v (Volts),i5v (amps),i3v (amps),last_command_id (),tc[0] (K),tc[1] (K),tc[2] (K),tc[3] (K),tc[4] (K),tc[5] (K),tc[6] (K),tc[7] (K),rtd[0] (K),rtd[1] (K),rtd[2] (K),rtd[3] (K),rtd[4] (K),rtd[5] (K),rtd[6] (K),rtd[7] (K),i_mtr_ab[0] (amps),i_mtr_ab[1] (amps),i_mtr_ab[2] (amps),i_mtr_ab[3] (amps),i_mtr[0] (amps),i_mtr[1] (amps),zero (Volts),zero (Volts),zero (Volts),zero (Volts),\n"
		self.valve_states = 0
		self.pressure = [0]*22
		self.samplerate = 0
		self.motor_setpoint = [0]*4
		self.main_cycle_time = 0
		self.motor_cycle_time = 0
		self.adc_cycle_time = 0
		self.telemetry_cycle_time = 0
		self.ebatt = 0
		self.LOG_TO_AUTO = 0
		self.auto_states = 0
		self.debug = [0]*8
		self.e5v = 0
		self.e3v = 0
		self.BOARD_ID = 0
		self.last_packet_number = -1
		self.last_command_id = -1
		self.imtr = [0]*2
		self.tbrd = 0
		self.tvlv = 0
		self.tmtr = 0
		self.error_code = 0
		self.LOGGING_ACTIVE = 0
		self.current_page = -1
		self.zero = 0
		self.e28v = 0
		self.i3v = 0
		self.i5v = 0
		self.log_string = ""
		self.num_items = 69
		
		self.dict = {}
		
		self.items = [''] * self.num_items
		self.items[0] = 'valve_states' 
		self.items[1] = 'pressure[0]' 
		self.items[2] = 'pressure[1]' 
		self.items[3] = 'pressure[2]' 
		self.items[4] = 'pressure[3]' 
		self.items[5] = 'pressure[4]' 
		self.items[6] = 'pressure[5]' 
		self.items[7] = 'pressure[6]' 
		self.items[8] = 'pressure[7]' 
		self.items[9] = 'ebatt' 
		self.items[10] = 'main_cycle_time' 
		self.items[11] = 'motor_cycle_time' 
		self.items[12] = 'adc_cycle_time' 
		self.items[13] = 'telemetry_cycle_time' 
		self.items[14] = 'load[2]' 
		self.items[15] = 'load[3]' 
		self.items[16] = 'telemetry_rate' 
		self.items[17] = 'load[5]' 
		self.items[18] = 'load[6]' 
		self.items[19] = 'load[7]' 
		self.items[20] = 'ivlv[0]' 
		self.items[21] = 'ivlv[1]' 
		self.items[22] = 'ivlv[2]' 
		self.items[23] = 'ivlv[3]' 
		self.items[24] = 'ivlv[4]' 
		self.items[25] = 'ivlv[5]' 
		self.items[26] = 'ivlv[6]' 
		self.items[27] = 'ivlv[7]' 
		self.items[28] = 'evlv[0]' 
		self.items[29] = 'evlv[1]' 
		self.items[30] = 'evlv[2]' 
		self.items[31] = 'evlv[3]' 
		self.items[32] = 'evlv[4]' 
		self.items[33] = 'evlv[5]' 
		self.items[34] = 'evlv[6]' 
		self.items[35] = 'evlv[7]' 
		self.items[36] = 'e3v' 
		self.items[37] = 'e5v' 
		self.items[38] = 'e28v' 
		self.items[39] = 'i5v' 
		self.items[40] = 'i3v' 
		self.items[41] = 'last_command_id' 
		self.items[42] = 'tc[0]' 
		self.items[43] = 'tc[1]' 
		self.items[44] = 'tc[2]' 
		self.items[45] = 'tc[3]' 
		self.items[46] = 'tc[4]' 
		self.items[47] = 'tc[5]' 
		self.items[48] = 'tc[6]' 
		self.items[49] = 'tc[7]' 
		self.items[50] = 'rtd[0]' 
		self.items[51] = 'rtd[1]' 
		self.items[52] = 'rtd[2]' 
		self.items[53] = 'rtd[3]' 
		self.items[54] = 'rtd[4]' 
		self.items[55] = 'rtd[5]' 
		self.items[56] = 'rtd[6]' 
		self.items[57] = 'rtd[7]' 
		self.items[58] = 'i_mtr_ab[0]' 
		self.items[59] = 'i_mtr_ab[1]' 
		self.items[60] = 'i_mtr_ab[2]' 
		self.items[61] = 'i_mtr_ab[3]' 
		self.items[62] = 'i_mtr[0]' 
		self.items[63] = 'i_mtr[1]' 
		self.items[64] = 'zero' 
		self.items[65] = 'zero' 
		self.items[66] = 'zero' 
		self.items[67] = 'zero' 

	def parse_packet(self, packet):
		byte_rep = packet[0:4]
		self.valve_states = int((float(struct.unpack("<I", byte_rep)[0]))/1)
		self.dict[self.items[0]] = self.valve_states
		byte_rep = packet[4:6]
		self.pressure[0] = float((float(struct.unpack("<h", byte_rep)[0]))/1)
		self.dict[self.items[1]] = self.pressure[0]
		byte_rep = packet[6:8]
		self.pressure[1] = float((float(struct.unpack("<h", byte_rep)[0]))/1)
		self.dict[self.items[2]] = self.pressure[1]
		byte_rep = packet[8:10]
		self.pressure[2] = float((float(struct.unpack("<h", byte_rep)[0]))/1)
		self.dict[self.items[3]] = self.pressure[2]
		byte_rep = packet[10:12]
		self.pressure[3] = float((float(struct.unpack("<h", byte_rep)[0]))/1)
		self.dict[self.items[4]] = self.pressure[3]
		byte_rep = packet[12:14]
		self.pressure[4] = float((float(struct.unpack("<h", byte_rep)[0]))/1)
		self.dict[self.items[5]] = self.pressure[4]
		byte_rep = packet[14:16]
		self.pressure[5] = float((float(struct.unpack("<h", byte_rep)[0]))/1)
		self.dict[self.items[6]] = self.pressure[5]
		byte_rep = packet[16:18]
		self.pressure[6] = float((float(struct.unpack("<h", byte_rep)[0]))/1)
		self.dict[self.items[7]] = self.pressure[6]
		byte_rep = packet[18:20]
		self.pressure[7] = float((float(struct.unpack("<h", byte_rep)[0]))/1)
		self.dict[self.items[8]] = self.pressure[7]
		byte_rep = packet[20:22]
		self.ebatt = float((float(struct.unpack("<h", byte_rep)[0]))/1000)
		self.dict[self.items[9]] = self.ebatt
		byte_rep = packet[22:24]
		self.main_cycle_time = int((float(struct.unpack("<h", byte_rep)[0]))/100)
		self.dict[self.items[10]] = self.main_cycle_time
		byte_rep = packet[24:25]
		self.motor_cycle_time = int((float(struct.unpack("<B", byte_rep)[0]))/1)
		self.dict[self.items[11]] = self.motor_cycle_time
		byte_rep = packet[25:27]
		self.adc_cycle_time = int((float(struct.unpack("<H", byte_rep)[0]))/1)
		self.dict[self.items[12]] = self.adc_cycle_time
		byte_rep = packet[27:29]
		self.telemetry_cycle_time = float((float(struct.unpack("<H", byte_rep)[0]))/1)
		self.dict[self.items[13]] = self.telemetry_cycle_time
		byte_rep = packet[29:31]
		self.load[2] = float((float(struct.unpack("<H", byte_rep)[0]))/1)
		self.dict[self.items[14]] = self.load[2]
		byte_rep = packet[31:33]
		self.load[3] = float((float(struct.unpack("<H", byte_rep)[0]))/1)
		self.dict[self.items[15]] = self.load[3]
		byte_rep = packet[33:35]
		self.telemetry_rate = float((float(struct.unpack("<H", byte_rep)[0]))/1)
		self.dict[self.items[16]] = self.telemetry_rate
		byte_rep = packet[35:37]
		self.load[5] = float((float(struct.unpack("<H", byte_rep)[0]))/1)
		self.dict[self.items[17]] = self.load[5]
		byte_rep = packet[37:39]
		self.load[6] = float((float(struct.unpack("<H", byte_rep)[0]))/1)
		self.dict[self.items[18]] = self.load[6]
		byte_rep = packet[39:41]
		self.load[7] = float((float(struct.unpack("<H", byte_rep)[0]))/1)
		self.dict[self.items[19]] = self.load[7]
		byte_rep = packet[41:42]
		self.ivlv[0] = float((float(struct.unpack("<B", byte_rep)[0]))/10)
		self.dict[self.items[20]] = self.ivlv[0]
		byte_rep = packet[42:43]
		self.ivlv[1] = float((float(struct.unpack("<B", byte_rep)[0]))/10)
		self.dict[self.items[21]] = self.ivlv[1]
		byte_rep = packet[43:44]
		self.ivlv[2] = float((float(struct.unpack("<B", byte_rep)[0]))/10)
		self.dict[self.items[22]] = self.ivlv[2]
		byte_rep = packet[44:45]
		self.ivlv[3] = float((float(struct.unpack("<B", byte_rep)[0]))/10)
		self.dict[self.items[23]] = self.ivlv[3]
		byte_rep = packet[45:46]
		self.ivlv[4] = float((float(struct.unpack("<B", byte_rep)[0]))/10)
		self.dict[self.items[24]] = self.ivlv[4]
		byte_rep = packet[46:47]
		self.ivlv[5] = float((float(struct.unpack("<B", byte_rep)[0]))/10)
		self.dict[self.items[25]] = self.ivlv[5]
		byte_rep = packet[47:48]
		self.ivlv[6] = float((float(struct.unpack("<B", byte_rep)[0]))/10)
		self.dict[self.items[26]] = self.ivlv[6]
		byte_rep = packet[48:49]
		self.ivlv[7] = float((float(struct.unpack("<B", byte_rep)[0]))/10)
		self.dict[self.items[27]] = self.ivlv[7]
		byte_rep = packet[49:50]
		self.evlv[0] = float((float(struct.unpack("<B", byte_rep)[0]))/10)
		self.dict[self.items[28]] = self.evlv[0]
		byte_rep = packet[50:51]
		self.evlv[1] = float((float(struct.unpack("<B", byte_rep)[0]))/10)
		self.dict[self.items[29]] = self.evlv[1]
		byte_rep = packet[51:52]
		self.evlv[2] = float((float(struct.unpack("<B", byte_rep)[0]))/10)
		self.dict[self.items[30]] = self.evlv[2]
		byte_rep = packet[52:53]
		self.evlv[3] = float((float(struct.unpack("<B", byte_rep)[0]))/10)
		self.dict[self.items[31]] = self.evlv[3]
		byte_rep = packet[53:54]
		self.evlv[4] = float((float(struct.unpack("<B", byte_rep)[0]))/10)
		self.dict[self.items[32]] = self.evlv[4]
		byte_rep = packet[54:55]
		self.evlv[5] = float((float(struct.unpack("<B", byte_rep)[0]))/10)
		self.dict[self.items[33]] = self.evlv[5]
		byte_rep = packet[55:56]
		self.evlv[6] = float((float(struct.unpack("<B", byte_rep)[0]))/10)
		self.dict[self.items[34]] = self.evlv[6]
		byte_rep = packet[56:57]
		self.evlv[7] = float((float(struct.unpack("<B", byte_rep)[0]))/10)
		self.dict[self.items[35]] = self.evlv[7]
		byte_rep = packet[57:61]
		self.e3v = float((float(struct.unpack("<i", byte_rep)[0]))/100)
		self.dict[self.items[36]] = self.e3v
		byte_rep = packet[61:65]
		self.e5v = float((float(struct.unpack("<i", byte_rep)[0]))/100)
		self.dict[self.items[37]] = self.e5v
		byte_rep = packet[65:67]
		self.e28v = float((float(struct.unpack("<h", byte_rep)[0]))/100)
		self.dict[self.items[38]] = self.e28v
		byte_rep = packet[67:68]
		self.i5v = float((float(struct.unpack("<B", byte_rep)[0]))/100)
		self.dict[self.items[39]] = self.i5v
		byte_rep = packet[68:69]
		self.i3v = float((float(struct.unpack("<B", byte_rep)[0]))/100)
		self.dict[self.items[40]] = self.i3v
		byte_rep = packet[69:71]
		self.last_command_id = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[41]] = self.last_command_id
		byte_rep = packet[71:73]
		self.tc[0] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[42]] = self.tc[0]
		byte_rep = packet[73:75]
		self.tc[1] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[43]] = self.tc[1]
		byte_rep = packet[75:77]
		self.tc[2] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[44]] = self.tc[2]
		byte_rep = packet[77:79]
		self.tc[3] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[45]] = self.tc[3]
		byte_rep = packet[79:81]
		self.tc[4] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[46]] = self.tc[4]
		byte_rep = packet[81:83]
		self.tc[5] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[47]] = self.tc[5]
		byte_rep = packet[83:85]
		self.tc[6] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[48]] = self.tc[6]
		byte_rep = packet[85:87]
		self.tc[7] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[49]] = self.tc[7]
		byte_rep = packet[87:89]
		self.rtd[0] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[50]] = self.rtd[0]
		byte_rep = packet[89:91]
		self.rtd[1] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[51]] = self.rtd[1]
		byte_rep = packet[91:93]
		self.rtd[2] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[52]] = self.rtd[2]
		byte_rep = packet[93:95]
		self.rtd[3] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[53]] = self.rtd[3]
		byte_rep = packet[95:97]
		self.rtd[4] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[54]] = self.rtd[4]
		byte_rep = packet[97:99]
		self.rtd[5] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[55]] = self.rtd[5]
		byte_rep = packet[99:101]
		self.rtd[6] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[56]] = self.rtd[6]
		byte_rep = packet[101:103]
		self.rtd[7] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[57]] = self.rtd[7]
		byte_rep = packet[103:105]
		self.i_mtr_ab[0] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[58]] = self.i_mtr_ab[0]
		byte_rep = packet[105:107]
		self.i_mtr_ab[1] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[59]] = self.i_mtr_ab[1]
		byte_rep = packet[107:109]
		self.i_mtr_ab[2] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[60]] = self.i_mtr_ab[2]
		byte_rep = packet[109:111]
		self.i_mtr_ab[3] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[61]] = self.i_mtr_ab[3]
		byte_rep = packet[111:113]
		self.i_mtr[0] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[62]] = self.i_mtr[0]
		byte_rep = packet[113:115]
		self.i_mtr[1] = float((float(struct.unpack("<H", byte_rep)[0]))/100)
		self.dict[self.items[63]] = self.i_mtr[1]
		byte_rep = packet[115:117]
		self.zero = float((float(struct.unpack("<H", byte_rep)[0]))/1000)
		self.dict[self.items[64]] = self.zero
		byte_rep = packet[117:119]
		self.zero = float((float(struct.unpack("<H", byte_rep)[0]))/1000)
		self.dict[self.items[65]] = self.zero
		byte_rep = packet[119:121]
		self.zero = float((float(struct.unpack("<H", byte_rep)[0]))/1000)
		self.dict[self.items[66]] = self.zero
		byte_rep = packet[121:123]
		self.zero = float((float(struct.unpack("<H", byte_rep)[0]))/1000)
		self.dict[self.items[67]] = self.zero
		self.log_string = str(time.clock())+','+str(self.valve_states)+','+str(self.pressure[0])+','+str(self.pressure[1])+','+str(self.pressure[2])+','+str(self.pressure[3])+','+str(self.pressure[4])+','+str(self.pressure[5])+','+str(self.pressure[6])+','+str(self.pressure[7])+','+str(self.ebatt)+','+str(self.main_cycle_time)+','+str(self.motor_cycle_time)+','+str(self.adc_cycle_time)+','+str(self.telemetry_cycle_time)+','+str(self.load[2])+','+str(self.load[3])+','+str(self.telemetry_rate)+','+str(self.load[5])+','+str(self.load[6])+','+str(self.load[7])+','+str(self.ivlv[0])+','+str(self.ivlv[1])+','+str(self.ivlv[2])+','+str(self.ivlv[3])+','+str(self.ivlv[4])+','+str(self.ivlv[5])+','+str(self.ivlv[6])+','+str(self.ivlv[7])+','+str(self.evlv[0])+','+str(self.evlv[1])+','+str(self.evlv[2])+','+str(self.evlv[3])+','+str(self.evlv[4])+','+str(self.evlv[5])+','+str(self.evlv[6])+','+str(self.evlv[7])+','+str(self.e3v)+','+str(self.e5v)+','+str(self.e28v)+','+str(self.i5v)+','+str(self.i3v)+','+str(self.last_command_id)+','+str(self.tc[0])+','+str(self.tc[1])+','+str(self.tc[2])+','+str(self.tc[3])+','+str(self.tc[4])+','+str(self.tc[5])+','+str(self.tc[6])+','+str(self.tc[7])+','+str(self.rtd[0])+','+str(self.rtd[1])+','+str(self.rtd[2])+','+str(self.rtd[3])+','+str(self.rtd[4])+','+str(self.rtd[5])+','+str(self.rtd[6])+','+str(self.rtd[7])+','+str(self.i_mtr_ab[0])+','+str(self.i_mtr_ab[1])+','+str(self.i_mtr_ab[2])+','+str(self.i_mtr_ab[3])+','+str(self.i_mtr[0])+','+str(self.i_mtr[1])+','+str(self.zero)+','+str(self.zero)+','+str(self.zero)+','+str(self.zero)+','