"""
MASA pressure transducer calibration generator script

Michigan Aeronautical Science Association
Author: Leif Gullstad (leifg@umich.edu)
Created: December 20, 2020 
Updated: December 21, 2020

Program expects input file to be a csv formatted as ID,Slope,offset
"""
import time
import sys
import csv

# Used to split() lines into columns
COLUMN_DELIMITER = ','

def main():

    # Autogeneration label and timestamp
    begin_autogen_tag = "/// BEGIN AUTOGENERATED SECTION - MODIFICATIONS TO THIS CODE WILL BE OVERWRITTEN\n"
    end_autogen_tag = "/// END AUTOGENERATED SECTION - USER CODE GOES BELOW THIS LINE\n"
    autogen_label = "/// Autogenerated by pt_calibration_generator.py on " + time.ctime()

    # Don't think I need to create a globals file
    # If globals needed, generate here

    # Struct definition
    struct_def = "struct Pt_calib {\n\tdouble slope;\n\tdouble offset;\n};"

    # Strings to hold what I want printed into the file
    pack_pt_calibration_h_str = ""
    pack_pt_calibration_c_str = ""

    pack_pt_calibration_h_str += begin_autogen_tag + "\n/// pack_pt_calibration.h\n" + autogen_label + "\n\n"
    pack_pt_calibration_h_str += struct_def + "\n\n"
    pack_pt_calibration_h_str += "extern void pt_calibration_data(struct Pt_calib* data);\n\n"
    pack_pt_calibration_h_str += "extern void update_temp(struct Pt_calib *temp, double slope, double offset);\n\n" \
    + "struct Pt_calib temp = {0,0};\n\n"


    pack_pt_calibration_c_str += begin_autogen_tag + "\n/// pack_pt_calibration.c\n" + autogen_label + "\n\n"

    pack_pt_calibration_c_str += "#include \"../inc/pack_pt_calibration.h\"\n\n"
    # pack_pt_calibration_c_str += "struct Pt_calib temp;\n\n"
    # pack_pt_calibration_c_str += "void update_temp(struct Pt_calib* temp, double slope_in, double offset_in) {\n" \
    # + "\ttemp->slope = slope_in;\n\ttemp->offset = offset_in;\n}\n\n"
    pack_pt_calibration_c_str += "void pt_calibration_data(struct Pt_calib* data) {\n"

    # Loop through csv file using iterator
    # Hard coded filename. Should be passed in as command line arg
    channel_num = -1
    with open('pt_calibration.csv') as csvfile:
        data_iter = csv.reader(csvfile, delimiter = COLUMN_DELIMITER)
        for row in data_iter:
            if (channel_num != -1): # Skips first row with column titles
                pack_pt_calibration_c_str += "\tdata[" + str(channel_num) + "] = CHANNEL_" + str(channel_num) + "_CALIBS;\n"
                pack_pt_calibration_h_str += "temp = {" + str(row[1]) + ", " + str(row[2]) + "};\n"
                pack_pt_calibration_h_str += "#define CHANNEL_" + str(channel_num) + "_CALIBS temp\n"
            channel_num += 1

    pack_pt_calibration_c_str += "}"

    # Print file strings to files
    pack_pt_calibration_h = open("../inc/pack_pt_calibration.h", "w+")
    pack_pt_calibration_h.write(pack_pt_calibration_h_str)
    pack_pt_calibration_c = open("../src/pack_pt_calibration.c", "w+")
    pack_pt_calibration_c.write(pack_pt_calibration_c_str)



if __name__ == '__main__':
    main()
