// will be autogenerated from byte_template_packet.txt file
#include "comms.h"
/* TODO: DELETE LATER ONCE TESTING IS DONE */
uint16_t pressures[2] = { 0x1234, 0x5678 };
uint8_t test            = 3;

#define NUM_TELEM_ITEMS     5
#define TELEM_ITEM_0 ((int16_t) (pressure[0]*1)) >> 0
#define TELEM_ITEM_1 ((int16_t) (pressure[0]*1)) >> 8
#define TELEM_ITEM_2 ((int16_t) (pressure[1]*1)) >> 0
#define TELEM_ITEM_3 ((int16_t) (pressure[1]*1)) >> 8
#define TELEM_ITEM_4 (uint8_t) test
