/// BEGIN AUTOGENERATED SECTION - MODIFICATIONS TO THIS CODE WILL BE OVERWRITTEN

/// pack_pt_calibration.c
/// Autogenerated by pt_calibration_generator.py on Mon Dec 21 15:33:08 2020

#include "../inc/pack_pt_calibration.h"

struct Pt_calib temp;

void update_temp(struct Pt_calib* temp, double slope_in, double offset_in) {
	temp->slope = slope_in;
	temp->offset = offset_in;
}

void pt_calibration_data(struct Pt_calib* data) {
	/// Column names are: ID,Slope,Offset
	update_temp(&temp, 0.64453125, 310.3030303);
	data[0] = temp;
	update_temp(&temp, 0.64453125, 310.3030303);
	data[1] = temp;
	update_temp(&temp, 0.64453125, 310.3030303);
	data[2] = temp;
	update_temp(&temp, 0.120849609, 310.3030303);
	data[3] = temp;
	update_temp(&temp, 0.351710858, 310.3030303);
	data[4] = temp;
	update_temp(&temp, 0.350960125, 310.3030303);
	data[5] = temp;
	update_temp(&temp, 0.000000000, 0);
	data[6] = temp;
	update_temp(&temp, 0.02678833, 466.6210982);
	data[7] = temp;
	update_temp(&temp, 0.013394165, 466.6210982);
	data[8] = temp;
	update_temp(&temp, 0.42861328, 466.6210982);
	data[9] = temp;
	update_temp(&temp, 0.08036499, 466.6210982);
	data[10] = temp;
	update_temp(&temp, 0.42861328, 466.6210982);
	data[11] = temp;
	update_temp(&temp, 0.64453125, 310.3030303);
	data[12] = temp;
	update_temp(&temp, 2.416992188, 310.3030303);
	data[13] = temp;
	update_temp(&temp, 2.416992188, 310.3030303);
	data[14] = temp;
	update_temp(&temp, 0, 0);
	data[15] = temp;
	update_temp(&temp, -2.84020000, 2048);
	data[16] = temp;
	update_temp(&temp, -2.84020000, 2048);
	data[17] = temp;
	update_temp(&temp, -2.84020000, 2048);
	data[18] = temp;
}