### BEGIN AUTOGENERATED SECTION - MODIFICATIONS TO THIS CODE WILL BE OVERWRITTEN

### s2_command.py
### Autogenerated by telem_defines_globals_generate.py on Tue Dec 22 20:18:34 2020

def s2_command(target_id, command_id, argc, argv):
	if (command_id == 8):
		pass
	elif (command_id == 9):
		pass
	elif (command_id == 10):
		pass
	elif (command_id == 11):
		pass
	elif (command_id == 12):
		pass
	elif (command_id == 13):
		pass
	elif (command_id == 14):
		pass
	elif (command_id == 15):
		pass
	elif (command_id == 16):
		pass
	elif (command_id == 17):
		pass
	elif (command_id == 18):
		pass
